name: AI Code Review with Auto-Fix PR

on:
  push:
    branches:
      - main

jobs:
  review-and-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          token: ${{ secrets.REGISTRY_TOKEN }}
      
      - name: Get diff and analyze
        run: |
          git diff HEAD^ HEAD > changes.diff
          
          if [ ! -s changes.diff ]; then
            echo "No changes to review"
            echo "HAS_CHANGES=false" >> $GITHUB_ENV
            exit 0
          fi
          
          echo "HAS_CHANGES=true" >> $GITHUB_ENV
          
          python3 -c "
          import json
          
          with open('changes.diff', 'r') as f:
              diff = f.read()
          
          prompt = '''Analyze this code diff for bugs, syntax errors, indentation issues, or improvements.

Return ONLY a JSON object:
{
  \"has_issues\": true/false,
  \"issues_summary\": \"brief description of issues found\",
  \"fixes\": [
    {
      \"file\": \"path/to/file\",
      \"description\": \"what was fixed\",
      \"fixed_content\": \"complete corrected file content\"
    }
  ]
}

If no issues: {\"has_issues\": false, \"issues_summary\": \"Code looks good\", \"fixes\": []}

Diff:
''' + diff
          
          request = {
              'contents': [{
                  'parts': [{
                      'text': prompt
                  }]
              }]
          }
          
          with open('request.json', 'w') as f:
              json.dump(request, f)
          "
          
          curl -s -X POST \
            "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${{ secrets.GEMINI_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d @request.json > response.json
          
          python3 << 'PYTHON'
          import json
          import re
          
          with open('response.json', 'r') as f:
              data = json.load(f)
          
          try:
              response_text = data['candidates'][0]['content']['parts'][0]['text']
              
              json_match = re.search(r'```json\s*(\{.*?\})\s*```', response_text, re.DOTALL)
              if json_match:
                  response_text = json_match.group(1)
              
              analysis = json.loads(response_text)
              
              with open('analysis.json', 'w') as f:
                  json.dump(analysis, f, indent=2)
              
              print(json.dumps(analysis, indent=2))
              
          except Exception as e:
              print(f"Analysis failed: {e}")
              with open('analysis.json', 'w') as f:
                  json.dump({"has_issues": False, "issues_summary": "Analysis error", "fixes": []}, f)
          PYTHON
      
      - name: Create fix branch and apply fixes
        if: env.HAS_CHANGES == 'true'
        run: |
          python3 << 'PYTHON'
          import json
          import os
          import subprocess
          
          with open('analysis.json', 'r') as f:
              analysis = json.load(f)
          
          if not analysis.get('has_issues', False):
              print("No issues to fix")
              with open('pr_needed.txt', 'w') as f:
                  f.write('false')
              exit(0)
          
          fixes = analysis.get('fixes', [])
          if not fixes:
              print("No fixes to apply")
              with open('pr_needed.txt', 'w') as f:
                  f.write('false')
              exit(0)
          
          # Create fix branch
          commit_sha = os.environ['GITHUB_SHA'][:7]
          branch_name = f"ai-fix-{commit_sha}"
          
          subprocess.run(['git', 'config', 'user.name', 'AI Code Fixer'], check=True)
          subprocess.run(['git', 'config', 'user.email', 'ai@gitea.local'], check=True)
          subprocess.run(['git', 'checkout', '-b', branch_name], check=True)
          
          # Apply fixes
          for fix in fixes:
              file_path = fix['file']
              fixed_content = fix['fixed_content']
              
              with open(file_path, 'w') as f:
                  f.write(fixed_content)
              
              print(f"Fixed: {file_path}")
          
          # Commit changes
          subprocess.run(['git', 'add', '-A'], check=True)
          
          issues_summary = analysis.get('issues_summary', 'Code improvements')
          commit_message = f"🤖 AI Auto-fix: {issues_summary}"
          
          subprocess.run(['git', 'commit', '-m', commit_message], check=True)
          subprocess.run(['git', 'push', 'origin', branch_name], check=True)
          
          # Save info for PR creation
          with open('pr_needed.txt', 'w') as f:
              f.write('true')
          with open('branch_name.txt', 'w') as f:
              f.write(branch_name)
          with open('pr_title.txt', 'w') as f:
              f.write(f"🤖 AI Code Fixes: {issues_summary}")
          
          # Create PR body
          pr_body = f"## AI Detected Issues\n\n{issues_summary}\n\n## Fixes Applied\n\n"
          for fix in fixes:
              pr_body += f"- **{fix['file']}**: {fix['description']}\n"
          pr_body += "\n---\n*This PR was automatically created by AI code review. Please review the changes before merging.*"
          
          with open('pr_body.txt', 'w') as f:
              f.write(pr_body)
          
          PYTHON
      
      - name: Create Pull Request
        if: env.HAS_CHANGES == 'true'
        run: |
          PR_NEEDED=$(cat pr_needed.txt 2>/dev/null || echo "false")
          
          if [ "$PR_NEEDED" != "true" ]; then
            echo "No PR needed"
            exit 0
          fi
          
          BRANCH=$(cat branch_name.txt)
          TITLE=$(cat pr_title.txt)
          BODY=$(cat pr_body.txt)
          
          # Create PR via Gitea API
          PR_RESPONSE=$(curl -X POST \
            "https://gitea.bothmainc.com/api/v1/repos/${{ github.repository }}/pulls" \
            -H "Authorization: token ${{ secrets.REGISTRY_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{
              \"title\": \"${TITLE}\",
              \"body\": \"${BODY}\",
              \"head\": \"${BRANCH}\",
              \"base\": \"main\"
            }")
          
          echo "$PR_RESPONSE" > pr_response.json
          
          PR_NUMBER=$(echo "$PR_RESPONSE" | jq -r '.number')
          PR_URL=$(echo "$PR_RESPONSE" | jq -r '.html_url')
          
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          echo "PR_URL=$PR_URL" >> $GITHUB_ENV
          
          echo "Created PR #$PR_NUMBER: $PR_URL"
      
      - name: Notify Gotify
        if: always()
        run: |
          PR_NEEDED=$(cat pr_needed.txt 2>/dev/null || echo "false")
          
          if [ "$PR_NEEDED" = "true" ] && [ -n "${{ env.PR_URL }}" ]; then
            TITLE="🤖 AI Fix PR Created"
            MESSAGE="A pull request with AI-suggested fixes has been created.\n\nPR #${{ env.PR_NUMBER }}\n${{ env.PR_URL }}\n\nReview and merge if the fixes look good."
            PRIORITY=6
          elif [ "${{ env.HAS_CHANGES }}" = "true" ]; then
            TITLE="✅ Code Review: No Issues"
            MESSAGE="AI reviewed your code and found no issues."
            PRIORITY=3
          else
            TITLE="ℹ️ Code Review Skipped"
            MESSAGE="No changes to review."
            PRIORITY=2
          fi
          
          curl -X POST "http://10.0.0.100:2580/message?token=120ff2" \
            -H "Content-Type: application/json" \
            -d "{\"title\": \"${TITLE}\", \"message\": \"${MESSAGE}\", \"priority\": ${PRIORITY}}"
