name: AI Autofix (Gemini, PR-only)

on:
  push:
    branches:
      - main

jobs:
  ai-autofix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Generate commit diff
        run: |
          git diff HEAD^ HEAD > changes.diff
          if [ ! -s changes.diff ]; then
            echo "No changes detected"
            exit 0
          fi

      - name: Build Gemini request
        run: |
          python3 << 'EOF'
          import json, textwrap

          try:
              with open("changes.diff", "r") as f:
                  diff = f.read()
          except FileNotFoundError:
              diff = ""

          prompt = textwrap.dedent("""\
          You are an automated code-fixing system.

          STRICT RULES:
          - Output ONLY a valid unified diff
          - NO markdown (do not use ```diff blocks)
          - NO explanations
          - NO commentary
          - NO surrounding text
          - If no fix is required, output exactly: NO_CHANGES

          Fix bugs, security issues, or correctness problems if present.

          Diff:
          """) + diff

          request = {
            "contents": [{
              "parts": [{"text": prompt}]
            }]
          }

          with open("request.json", "w") as f:
            json.dump(request, f)
          EOF

      - name: Call Gemini API
        env:
          # Mapping secret to ENV var prevents curl parsing errors
          GEMINI_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          curl -sS -X POST \
            "[https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=$GEMINI_KEY](https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=$GEMINI_KEY)" \
            -H "Content-Type: application/json" \
            -d @request.json > response.json

      - name: Extract and normalize unified diff
        run: |
          python3 << 'EOF'
          import json, sys

          try:
              with open("response.json") as f:
                  data = json.load(f)
              
              if "candidates" not in data:
                  print("Error: API response does not contain candidates.")
                  # Dump response for debugging
                  print(json.dumps(data, indent=2))
                  sys.exit(1)
                  
              text = data["candidates"][0]["content"]["parts"][0]["text"]
          except Exception as e:
              print(f"Error parsing Gemini response: {e}")
              sys.exit(1)

          text = text.strip()

          if text == "NO_CHANGES" or not text:
              open("ai.patch", "w").write("")
              sys.exit(0)

          # Strip markdown code fences if present
          lines = text.splitlines()
          if lines and lines[0].startswith("```"):
              lines = lines[1:]
          if lines and lines[-1].startswith("```"):
              lines = lines[:-1]

          start = None
          for i, line in enumerate(lines):
              if line.startswith("diff --git") or line.startswith("--- "):
                  start = i
                  break

          if start is None:
              print("No unified diff found in AI output")
              sys.exit(1)

          patch = "\n".join(lines[start:])
          with open("ai.patch", "w") as f:
              f.write(patch)
          EOF

      - name: Validate patch with git
        run: |
          if [ ! -s ai.patch ]; then
            echo "No AI changes to apply."
            exit 0
          fi
          git apply --check ai.patch

      - name: Apply patch and commit
        run: |
          if [ ! -s ai.patch ]; then
            exit 0
          fi
          
          SHA="${GITEA_SHA:-$GITHUB_SHA}"
          NEW_BRANCH="ai-fix-${SHA:0:7}"
          
          git config --global user.name "AI Autofix Bot"
          git config --global user.email "ai-bot@noreply.gitea.io"

          git checkout -b "$NEW_BRANCH"
          git apply ai.patch
          git commit -am "AI autofix for ${SHA:0:7}"
          git push origin "$NEW_BRANCH"

          # Export variable for Gitea/GitHub Actions compatibility
          echo "AI_BRANCH=$NEW_BRANCH" >> $GITHUB_ENV
          [ -n "$GITEA_ENV" ] && echo "AI_BRANCH=$NEW_BRANCH" >> "$GITEA_ENV"

      - name: Create Gitea pull request
        if: success()
        env:
          G_TOKEN: ${{ secrets.GITEA_TOKEN }}
        run: |
          if [ -z "$AI_BRANCH" ]; then exit 0; fi

          REPO_PATH="${GITEA_REPOSITORY:-$GITHUB_REPOSITORY}"
          OWNER=$(echo "$REPO_PATH" | cut -d/ -f1)
          REPO=$(echo "$REPO_PATH" | cut -d/ -f2)
          API_BASE="${GITEA_URL:-$GITHUB_API_URL}"

          curl -sS -X POST \
            "${API_BASE}/api/v1/repos/${OWNER}/${REPO}/pulls" \
            -H "Authorization: token $G_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{
              \"title\": \"AI Autofix\",
              \"head\": \"${AI_BRANCH}\",
              \"base\": \"main\",
              \"body\": \"Automated AI-generated fix.\"
            }"

      - name: Notify Gotify
        if: always()
        env:
          GOTIFY_TOKEN: ${{ secrets.GOTIFY_TOKEN }}
        run: |
          if [ -n "$GOTIFY_TOKEN" ]; then
            curl -X POST "${{ secrets.GOTIFY_URL }}/message?token=$GOTIFY_TOKEN" \
              -H "Content-Type: application/json" \
              -d "{
                \"title\": \"AI Autofix Job Finished\",
                \"message\": \"Repo: ${GITEA_REPOSITORY:-$GITHUB_REPOSITORY}\",
                \"priority\": 5
              }"
          fi