name: AI Autofix (Gemini, PR-only)

on:
  push:
    branches:
      - main

jobs:
  ai-autofix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Generate commit diff
        run: |
          git diff HEAD^ HEAD > changes.diff
          if [ ! -s changes.diff ]; then
            echo "No changes detected"
            exit 0
          fi

      - name: Build Gemini request
        run: |
          python3 << 'EOF'
          import json, textwrap

          try:
              with open("changes.diff", "r") as f:
                  diff = f.read()
          except FileNotFoundError:
              diff = ""

          prompt = textwrap.dedent("""\
          You are an automated code-fixing system.

          STRICT RULES:
          - Output ONLY a valid unified diff
          - NO markdown (do not use ```diff blocks)
          - NO explanations
          - NO commentary
          - NO surrounding text
          - If no fix is required, output exactly: NO_CHANGES

          Fix bugs, security issues, or correctness problems if present.

          Diff:
          """) + diff

          request = {
            "contents": [{
              "parts": [{"text": prompt}]
            }]
          }

          with open("request.json", "w") as f:
            json.dump(request, f)
          EOF

      - name: Call Gemini API
        run: |
          # -g disables globbing to prevent "bad range" error with curly braces
          curl -g -sS -X POST \
            '[https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=$](https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=$){{ secrets.GEMINI_API_KEY }}' \
            -H "Content-Type: application/json" \
            -d @request.json > response.json

      - name: Extract and normalize unified diff
        run: |
          python3 << 'EOF'
          import json, sys

          try:
              with open("response.json") as f:
                  data = json.load(f)
              text = data["candidates"][0]["content"]["parts"][0]["text"]
          except Exception as e:
              print(f"Error parsing Gemini response: {e}")
              # Print response to logs for debugging
              with open("response.json") as f:
                  print(f.read())
              sys.exit(1)

          text = text.strip()

          if text == "NO_CHANGES" or not text:
              open("ai.patch