name: Build and Push Docker Image

on:
  workflow_dispatch:   # Manual "Run workflow" button only

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Gitea Container Registry
        uses: docker/login-action@v3
        with:
          registry: gitea.bothmainc.com
          username: Cbothma
          password: Lilly@057!

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./dockup             # Folder containing Dockerfile and needed files
          file: ./dockup/Dockerfile     # Exact path to your Dockerfile
          push: true
          tags: |
            gitea.bothmainc.com/cbothma/dockup:latest
            gitea.bothmainc.com/cbothma/dockup:${{ gitea.sha }}

      - name: Send Gotify Notification
        if: always()  # Runs on success, failure, or cancelled
        uses: eikendev/gotify-action@v1
        with:
          gotify_api_base: ${{ secrets.GOTIFY_URL }}      # e.g., https://gotify.yourdomain.com
          gotify_app_token: ${{ secrets.GOTIFY_TOKEN }}   # Your Gotify app token
          notification_title: "Dockup Build ${{ job.status }}"
          notification_message: |
            Repository: ${{ gitea.repository }}
            Commit: ${{ gitea.sha }}
            Status: ${{ job.status }}
            Run: https://gitea.bothmainc.com/\( {{ gitea.repository }}/actions/runs/ \){{ gitea.run_id }}
          notification_priority: 5  # 1-10, higher = more urgent