name: Build and Push Docker Image (DockerHub)

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Gitea Container Registry
        uses: docker/login-action@v3
        with:
          registry: gitea.bothmainc.com
          username: Cbothma
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
            -u "${{ secrets.DOCKERHUB_USERNAME }}" \
            --password-stdin

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./dockup
          file: ./dockup/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            cbothma/dockup:latest
            cbothma/dockup:1.2.9

      - name: Notify Gotify
        if: always()
        run: |
          TITLE="🐳 DockerHub Push: dockup"
          MESSAGE="Platform: linux/amd64\nRegistry: DockerHub\nTags: latest, 1.2.9\nStatus: ${{ job.status }}"
          
          if [ "${{ job.status }}" = "success" ]; then
            PRIORITY=4
          else
            PRIORITY=8
          fi
          
          curl -X POST "http://10.0.0.100:2580/message?token=120ff2" \
            -H "Content-Type: application/json" \
            -d "{\"title\": \"${TITLE}\", \"message\": \"${MESSAGE}\", \"priority\": ${PRIORITY}}"
