name: Build and Push Docker Image (DockerHub Multi-Arch)

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU for multi-arch builds
        uses: docker/setup-qemu-action@v3
        with:
          image: gitea.bothmainc.com/cbothma/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Gitea Container Registry
        uses: docker/login-action@v3
        with:
          registry: gitea.bothmainc.com
          username: Cbothma
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
            -u "${{ secrets.DOCKERHUB_USERNAME }}" \
            --password-stdin

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: ./dockup
          file: ./dockup/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            cbothma/dockup:latest
            cbothma/dockup:1.4.0
          cache-from: type=registry,ref=gitea.bothmainc.com/cbothma/dockup:buildcache
          cache-to: type=registry,ref=gitea.bothmainc.com/cbothma/dockup:buildcache,mode=max

      - name: Build summary
        run: |
          echo "✅ Multi-arch build complete!"
          echo "🗂️  Platforms: linux/amd64, linux/arm64"
          echo "📦 Pushed to DockerHub: cbothma/dockup:latest"
          echo "📦 Pushed to DockerHub: cbothma/dockup:1.3.8"
          echo "💾 Cache stored in Gitea registry (not DockerHub)"

      - name: Notify Gotify
        if: always()
        run: |
          TITLE="🐳 DockerHub Multi-Arch: dockup"
          MESSAGE="Platforms: amd64 + arm64\nRegistry: DockerHub\nTags: latest, 1.3.0\nStatus: ${{ job.status }}"
          
          if [ "${{ job.status }}" = "success" ]; then
            PRIORITY=4
          else
            PRIORITY=8
          fi
          
          curl -X POST "http://10.0.0.100:2580/message?token=120ff2" \
            -H "Content-Type: application/json" \
            -d "{\"title\": \"${TITLE}\", \"message\": \"${MESSAGE}\", \"priority\": ${PRIORITY}}"
