name: Build and Push Docker Image (DockerHub)

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # KEEP AS REQUESTED
      - name: Login to Gitea Container Registry
        uses: docker/login-action@v3
        with:
          registry: gitea.bothmainc.com
          username: Cbothma
          password: Lilly@057!

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
            -u "${{ secrets.DOCKERHUB_USERNAME }}" \
            --password-stdin

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./dockup
          file: ./dockup/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            cbothma/dockup:latest