name: Build and Push Docker Image (Multi-Arch)

on:
  workflow_dispatch:   # Manual "Run workflow" button only

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU for multi-arch builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Gitea Container Registry
        uses: docker/login-action@v3
        with:
          registry: gitea.bothmainc.com
          username: Cbothma
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push multi-arch
        uses: docker/build-push-action@v5
        with:
          context: ./dockup             # Folder containing Dockerfile and needed files
          file: ./dockup/Dockerfile     # Exact path to your Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            gitea.bothmainc.com/cbothma/dockup:latest
            gitea.bothmainc.com/cbothma/dockup:${{ gitea.sha }}
          cache-from: type=registry,ref=gitea.bothmainc.com/cbothma/dockup:buildcache
          cache-to: type=registry,ref=gitea.bothmainc.com/cbothma/dockup:buildcache,mode=max

      - name: Build summary
        run: |
          echo "✅ Multi-arch build complete!"
          echo "🏗️  Platforms: linux/amd64, linux/arm64"
          echo "📦 Pushed to: gitea.bothmainc.com/cbothma/dockup:latest"
